spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_app
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    password: bxzk wzsc vdnk wldk
    username: minh.hacker89@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 3000
  servlet:
    context-path: /api/v1

jwt:
  signerKey-access: zN/gkNC3dQIrDfQQ2Yyv9zo/OyEc6t/BjI20zDPNY+v2i1W69TVL2rJNJkXsGLi7
  signerKey-refresh: pR8yHfW1vL4zQsB7mK9uXeAt/J0cD5oGnZh2TwMj+Yl3NbVqCrUsOxEiFg6PaRdSk
  valid-duration: 300
  refreshable-duration: 604800

role:
  user: 6e214db3-7089-40de-9649-eae6ff295fc3
  admin: cc2f31f4-ab20-41d0-a3e9-1b49ea5608f5

file:
  upload-dir: public/images

track:
  upload-dir: public/tracks
